FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose port
ENV PORT=3333
EXPOSE 3333

# Start development server
CMD ["npm", "start"]
